"""
Biomedical knowledge base for OncoTargetMind.
Contains variant-drug mappings, gene druggability, and cancer-type associations.
"""

# Variant → matched drugs with evidence level and specificity
VARIANT_DRUG_MAP: dict[str, dict] = {
    "BRAF V600E": {
        "drugs": ["Vemurafenib", "Dabrafenib", "Encorafenib"],
        "evidence": 10,
        "specificity": 9,
        "druggability": 10,
        "category": "direct_inhibitor",
        "rationale": "FDA-approved BRAF inhibitor with high response rates in BRAF V600E-mutant melanoma, NSCLC, and thyroid cancer.",
    },
    "EGFR L858R": {
        "drugs": ["Osimertinib", "Gefitinib", "Erlotinib"],
        "evidence": 10,
        "specificity": 8,
        "druggability": 10,
        "category": "direct_inhibitor",
        "rationale": "FDA-approved EGFR TKI. Osimertinib preferred for first-line EGFR-mutant NSCLC.",
    },
    "EGFR exon19del": {
        "drugs": ["Osimertinib", "Gefitinib", "Erlotinib"],
        "evidence": 10,
        "specificity": 8,
        "druggability": 10,
        "category": "direct_inhibitor",
        "rationale": "FDA-approved EGFR TKI. Classic sensitizing EGFR mutation in NSCLC.",
    },
    "EGFR T790M": {
        "drugs": ["Osimertinib"],
        "evidence": 10,
        "specificity": 7,
        "druggability": 10,
        "category": "direct_inhibitor",
        "rationale": "Acquired resistance mutation. Osimertinib is specifically approved for T790M-positive NSCLC.",
    },
    "KRAS G12C": {
        "drugs": ["Sotorasib", "Adagrasib"],
        "evidence": 9,
        "specificity": 8,
        "druggability": 9,
        "category": "direct_inhibitor",
        "rationale": "FDA-approved KRAS G12C inhibitors for NSCLC and colorectal cancer.",
    },
    "KRAS G12D": {
        "drugs": ["MRTX1133 (investigational)"],
        "evidence": 5,
        "specificity": 7,
        "druggability": 5,
        "category": "direct_inhibitor",
        "rationale": "KRAS G12D is common in pancreatic and colorectal cancers. Inhibitors are in early clinical development.",
    },
    "ALK fusion": {
        "drugs": ["Alectinib", "Crizotinib", "Lorlatinib", "Brigatinib"],
        "evidence": 10,
        "specificity": 9,
        "druggability": 10,
        "category": "direct_inhibitor",
        "rationale": "Multiple FDA-approved ALK inhibitors. Alectinib is first-line for ALK+ NSCLC.",
    },
    "ROS1 fusion": {
        "drugs": ["Crizotinib", "Entrectinib"],
        "evidence": 9,
        "specificity": 8,
        "druggability": 9,
        "category": "direct_inhibitor",
        "rationale": "FDA-approved ROS1 inhibitors for ROS1-rearranged NSCLC.",
    },
    "RET fusion": {
        "drugs": ["Selpercatinib", "Pralsetinib"],
        "evidence": 9,
        "specificity": 8,
        "druggability": 9,
        "category": "direct_inhibitor",
        "rationale": "FDA-approved selective RET inhibitors with excellent CNS penetration.",
    },
    "MET exon14skip": {
        "drugs": ["Capmatinib", "Tepotinib"],
        "evidence": 9,
        "specificity": 7,
        "druggability": 9,
        "category": "direct_inhibitor",
        "rationale": "FDA-approved MET inhibitors for MET exon 14 skipping NSCLC.",
    },
    "IDH1 R132H": {
        "drugs": ["Ivosidenib"],
        "evidence": 9,
        "specificity": 8,
        "druggability": 9,
        "category": "direct_inhibitor",
        "rationale": "FDA-approved IDH1 inhibitor for AML and cholangiocarcinoma.",
    },
    "IDH2 R140Q": {
        "drugs": ["Enasidenib"],
        "evidence": 9,
        "specificity": 8,
        "druggability": 9,
        "category": "direct_inhibitor",
        "rationale": "FDA-approved IDH2 inhibitor for relapsed/refractory AML.",
    },
    "NTRK1 fusion": {
        "drugs": ["Larotrectinib", "Entrectinib"],
        "evidence": 10,
        "specificity": 8,
        "druggability": 10,
        "category": "direct_inhibitor",
        "rationale": "Tumor-agnostic FDA approval for NTRK fusion-positive solid tumors.",
    },
    "PIK3CA E545K": {
        "drugs": ["Alpelisib"],
        "evidence": 8,
        "specificity": 6,
        "druggability": 8,
        "category": "direct_inhibitor",
        "rationale": "FDA-approved PI3Kα inhibitor for PIK3CA-mutated HR+/HER2- breast cancer.",
    },
    "ERBB2 amp": {
        "drugs": ["Trastuzumab", "Trastuzumab Deruxtecan", "Lapatinib"],
        "evidence": 9,
        "specificity": 7,
        "druggability": 10,
        "category": "direct_inhibitor",
        "rationale": "Multiple approved HER2-targeted therapies. T-DXd shows efficacy across HER2-low to HER2+ tumors.",
    },
    "KIT D816V": {
        "drugs": ["Imatinib", "Sunitinib", "Ripretinib"],
        "evidence": 9,
        "specificity": 7,
        "druggability": 9,
        "category": "direct_inhibitor",
        "rationale": "FDA-approved KIT inhibitors for GIST. Imatinib is first-line.",
    },
    "BRCA1 mut": {
        "drugs": ["Olaparib", "Niraparib", "Rucaparib"],
        "evidence": 10,
        "specificity": 6,
        "druggability": 9,
        "category": "synthetic_lethality",
        "rationale": "PARP inhibitors exploit synthetic lethality in BRCA1-deficient tumors. FDA-approved for ovarian, breast, pancreatic, and prostate cancers.",
    },
    "BRCA2 mut": {
        "drugs": ["Olaparib", "Niraparib", "Rucaparib"],
        "evidence": 10,
        "specificity": 6,
        "druggability": 9,
        "category": "synthetic_lethality",
        "rationale": "PARP inhibitors exploit synthetic lethality in BRCA2-deficient tumors. FDA-approved across multiple cancer types.",
    },
}

# Gene druggability scores for over/under-expressed genes (not variant-specific)
GENE_DRUGGABILITY: dict[str, dict] = {
    "MYC": {
        "druggability": 3,
        "specificity": 4,
        "evidence": 5,
        "rationale": "MYC is a master transcription factor, historically undruggable. Indirect targeting via BET/Brd4 inhibitors or CDK9 inhibitors in early trials.",
        "drugs": ["BET inhibitors (investigational)", "Omomyc (preclinical)"],
    },
    "CCND1": {
        "druggability": 6,
        "specificity": 5,
        "evidence": 6,
        "rationale": "Encodes Cyclin D1. CDK4/6 inhibitors (Palbociclib, Ribociclib) indirectly target CCND1-CDK4/6 pathway.",
        "drugs": ["Palbociclib", "Ribociclib", "Abemaciclib"],
    },
    "EGFR": {
        "druggability": 10,
        "specificity": 7,
        "evidence": 8,
        "rationale": "EGFR overexpression is targetable with monoclonal antibodies (Cetuximab) or TKIs.",
        "drugs": ["Cetuximab", "Panitumumab", "Osimertinib"],
    },
    "ERBB2": {
        "druggability": 10,
        "specificity": 7,
        "evidence": 9,
        "rationale": "HER2 overexpression/amplification is a validated target in breast and gastric cancers.",
        "drugs": ["Trastuzumab", "Trastuzumab Deruxtecan", "Pertuzumab"],
    },
    "VEGFA": {
        "druggability": 9,
        "specificity": 5,
        "evidence": 8,
        "rationale": "VEGF-A is the primary target of Bevacizumab. Approved across multiple cancer types.",
        "drugs": ["Bevacizumab", "Aflibercept"],
    },
    "PDL1": {
        "druggability": 9,
        "specificity": 6,
        "evidence": 10,
        "rationale": "PD-L1 overexpression guides immunotherapy. Anti-PD-1/PD-L1 antibodies are standard of care.",
        "drugs": ["Pembrolizumab", "Nivolumab", "Atezolizumab"],
    },
    "BCL2": {
        "druggability": 8,
        "specificity": 6,
        "evidence": 8,
        "rationale": "BCL-2 overexpression drives survival in hematologic malignancies. Venetoclax is FDA-approved for CLL and AML.",
        "drugs": ["Venetoclax"],
    },
    "MDM2": {
        "druggability": 6,
        "specificity": 5,
        "evidence": 6,
        "rationale": "MDM2 negatively regulates p53. MDM2 inhibitors (Nutlins, Idasanutlin) in clinical trials.",
        "drugs": ["Idasanutlin (investigational)", "Milademetan (investigational)"],
    },
    "TP53": {
        "druggability": 2,
        "specificity": 3,
        "evidence": 4,
        "rationale": "TP53 loss is difficult to target directly. Strategies include restoring mutant p53 function (PRIMA-1/APR-246) or exploiting synthetic lethality (WEE1 inhibitors).",
        "drugs": ["APR-246 (investigational)", "Adavosertib (WEE1 inhibitor)"],
    },
    "RB1": {
        "druggability": 2,
        "specificity": 3,
        "evidence": 3,
        "rationale": "RB1 loss leads to E2F deregulation. CDK4/6 inhibitors may have limited effect in RB1-null tumors. Potential synthetic lethality with AURKA or CHK1 inhibitors.",
        "drugs": ["AURKA inhibitors (investigational)"],
    },
    "PTEN": {
        "druggability": 5,
        "specificity": 5,
        "evidence": 6,
        "rationale": "PTEN loss activates PI3K/AKT/mTOR pathway. mTOR inhibitors or AKT inhibitors may be effective.",
        "drugs": ["Everolimus", "Ipatasertib (investigational)"],
    },
    "CDKN2A": {
        "druggability": 3,
        "specificity": 4,
        "evidence": 4,
        "rationale": "p16 loss leads to CDK4/6 hyperactivity. CDK4/6 inhibitors may provide benefit.",
        "drugs": ["Palbociclib", "Ribociclib"],
    },
    "FGFR1": {
        "druggability": 8,
        "specificity": 6,
        "evidence": 7,
        "rationale": "FGFR1 amplification/overexpression is targetable with FGFR inhibitors.",
        "drugs": ["Erdafitinib", "Pemigatinib", "Futibatinib"],
    },
    "MET": {
        "druggability": 9,
        "specificity": 6,
        "evidence": 7,
        "rationale": "MET amplification/overexpression is targetable with MET inhibitors.",
        "drugs": ["Capmatinib", "Tepotinib", "Savolitinib"],
    },
}

# Down-regulated tumor suppressors → synthetic lethality strategies
DOWN_GENE_STRATEGIES: dict[str, dict] = {
    "TP53": {
        "strategy": "WEE1 inhibition or AURKA inhibition",
        "drugs": ["Adavosertib", "Alisertib (investigational)"],
        "druggability": 4,
        "specificity": 5,
        "evidence": 5,
        "rationale": "TP53 loss creates G1/S checkpoint deficiency, increasing reliance on G2/M checkpoint (WEE1). WEE1 inhibitors exploit this synthetic lethality.",
    },
    "RB1": {
        "strategy": "AURKA or CHK1 inhibition",
        "drugs": ["Alisertib (investigational)", "Prexasertib (investigational)"],
        "druggability": 3,
        "specificity": 4,
        "evidence": 4,
        "rationale": "RB1 loss creates dependency on AURKA and CHK1 for mitotic progression.",
    },
    "BRCA1": {
        "strategy": "PARP inhibition",
        "drugs": ["Olaparib", "Niraparib", "Rucaparib"],
        "druggability": 9,
        "specificity": 6,
        "evidence": 10,
        "rationale": "BRCA1 deficiency impairs homologous recombination repair, creating synthetic lethality with PARP inhibitors.",
    },
    "BRCA2": {
        "strategy": "PARP inhibition",
        "drugs": ["Olaparib", "Niraparib", "Rucaparib"],
        "druggability": 9,
        "specificity": 6,
        "evidence": 10,
        "rationale": "BRCA2 deficiency impairs homologous recombination repair, creating synthetic lethality with PARP inhibitors.",
    },
    "PTEN": {
        "strategy": "AKT or mTOR inhibition",
        "drugs": ["Ipatasertib (investigational)", "Everolimus"],
        "druggability": 6,
        "specificity": 5,
        "evidence": 6,
        "rationale": "PTEN loss leads to constitutive PI3K/AKT/mTOR signaling. AKT and mTOR inhibitors are in clinical trials.",
    },
    "STK11": {
        "strategy": "AMPK activation or metabolic targeting",
        "drugs": ["Metformin (investigational)", "Phenformin (investigational)"],
        "druggability": 2,
        "specificity": 4,
        "evidence": 3,
        "rationale": "STK11/LKB1 loss creates metabolic vulnerabilities. AMPK activators and OXPHOS inhibitors under investigation.",
    },
    "SMARCB1": {
        "strategy": "EZH2 inhibition",
        "drugs": ["Tazemetostat"],
        "druggability": 7,
        "specificity": 7,
        "evidence": 7,
        "rationale": "SMARCB1 loss creates dependency on EZH2. Tazemetostat is FDA-approved for epithelioid sarcoma.",
    },
    "CDKN2A": {
        "strategy": "CDK4/6 inhibition",
        "drugs": ["Palbociclib", "Ribociclib", "Abemaciclib"],
        "druggability": 7,
        "specificity": 5,
        "evidence": 6,
        "rationale": "CDKN2A/p16 loss leads to unopposed CDK4/6 activity, making CDK4/6 inhibitors a rational approach.",
    },
}